package edu.austral.ingsis.tokens;

public enum TokenType {

    LET,
    IDENTIFIER,
    SEMICOLON,
    COLON,
    EQUALS,
    NUMBER_TYPE,
    STRING_TYPE,
    L_PARENTHESES,
    R_PARANTHESES,
    ADDITION_OP,
    SUBTRACTION_OP,
    DIVISION_OP,
    MULTIPLICATION_OP,
    DOUBLE_QUOTATION,
    SINGLE_QUOTATION,
    STRING_LITERAL,
    NUMBER_LITERAL,
    PRINTLN;

}
