package edu.austral.ingsis.ast;

public enum TokenType {
    LOGICAL_EQUALS,
    GREATER_THAN,
    GREATER_THAN_EQUALS,
    LESS_THAN,
    LESS_THAN_EQUALS,
    LET,
    IDENTIFIER,
    SEMICOLON,
    COLON,
    EQUALS,
    TYPE,
    L_PARENTHESES,
    R_PARANTHESES,
    PLUS_SYMBOL,
    MINUS_SYMBOL,
    SLASH_SYMBOL,
    STAR_SYMBOL,
    CONST,
    DOUBLE_QUOTATION,
    SINGLE_QUOTATION,
    LITERAL,
    PRINTLN;
}
