package edu.austral.ingsis.tokens;

public enum TokenType {
  DOUBLE_EQUALS, //==
  GREATER_THAN, //>
  GREATER_THAN_EQUALS,
  LESS_THAN,
  NOT_EQUALS,
  LESS_THAN_EQUALS,
  IF, //if
  ELSE,
  L_CURLY_BRACE, // {
  R_CURLY_BRACE, // }
  LET,
  IDENTIFIER,
  SEMICOLON,
  COLON,
  EQUALS,
  TYPE,
  L_PARENTHESES,
  R_PARENTHESES,
  PLUS_SYMBOL,
  MINUS_SYMBOL,
  SLASH_SYMBOL,
  STAR_SYMBOL,
  CONST,
  DOUBLE_QUOTATION,
  SINGLE_QUOTATION,
  LITERAL,
  PRINTLN
}
